/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.amitsk.learnapcsa;

import java.util.logging.Logger;

public class Library {
    private static Logger logger = Logger.getLogger(Library.class.getName());
    public boolean someLibraryMethod() {
        logger.info(" Testing...");
        return true;
    }
}
